export const GALLERY_FETCH_REQUEST = 'GALLERY_FETCH_REQUEST';
export const GALLERY_FETCH_FAILURE = 'GALLERY_FETCH_FAILURE';
export const GALLERY_FETCH_SUCCESS = 'GALLERY_FETCH_SUCCESS';

export const MEDIA_SAVE_REQUEST = 'MEDIA_SAVE_REQUEST';
export const MEDIA_SAVE_FAILURE = 'MEDIA_SAVE_FAILURE';
export const MEDIA_SAVE_SUCCESS = 'MEDIA_SAVE_SUCCESS';

export const MEDIA_DELETE_REQUEST = 'MEDIA_DELETE_REQUEST';
export const MEDIA_DELETE_FAILURE = 'MEDIA_DELETE_FAILURE';
export const MEDIA_DELETE_SUCCESS = 'MEDIA_DELETE_SUCCESS';

export const GALLERY_PLAY_ITEM = 'GALLERY_PLAY_ITEM';
export const GALLERY_STOP_ITEM = 'GALLERY_STOP_ITEM';
